# Generated by Django 3.0.4 on 2020-03-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('param_type', models.CharField(max_length=200)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.parameters')),
            ],
        ),
    ]
