# Generated by Django 3.0.4 on 2020-03-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='form_id',
            new_name='param_id',
        ),
        migrations.CreateModel(
            name='values',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.forms')),
                ('param_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.parameters')),
            ],
        ),
    ]
