# Generated by Django 3.0.4 on 2020-03-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200322_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='param_id',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='values',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='values',
            name='param_id',
        ),
        migrations.AddField(
            model_name='options',
            name='param',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.Parameters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.Forms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='values',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='forms.Forms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='values',
            name='param',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='forms.Parameters'),
            preserve_default=False,
        ),
    ]
