# Generated by Django 3.0.4 on 2020-03-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200323_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Parameters'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Forms'),
        ),
        migrations.AlterField(
            model_name='values',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Forms'),
        ),
        migrations.AlterField(
            model_name='values',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Parameters'),
        ),
    ]
